=== ChrisRG/ReadingHamlet/RHschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="transcription">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="page"/>
        <xs:element ref="annotation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="page">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.page"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.page">
    <xs:attribute name="filename" use="required"/>
    <xs:attribute name="pagination" use="required"/>  <!-- Made required for Reading Hamlet -->
    <xs:attribute name="signature"/>
    <xs:attribute name="reader" use="required"/>
  </xs:attributeGroup>
  <xs:element name="annotation">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="marginalia"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="substitution"/> <!-- Added for Reading Hamlet-->
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="underline"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="symbol"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="mark"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="numeral"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="errata"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="drawing"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="marginalia">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="language"/>
        <xs:element minOccurs="0" ref="translation"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.marginalia"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.marginalia">
    <xs:attribute name="hand"> <!-- Removed requirement for Reading Hamlet -->
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="English_secretary"/>
          <xs:enumeration value="Italian"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="marginalia_id"/>
    <xs:attribute name="marginalia_continues_to"/>
    <xs:attribute name="marginalia_continues_from"/>
    <xs:attribute name="marginalia_to_transcription"/>
    <xs:attribute name="marginalia_from_transcription"/>
    <xs:attribute name="book_id"/>
    <xs:attribute name="date"/>
    <xs:attribute name="other_reader"/>
    <xs:attribute name="topic">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Law"/>
          <xs:enumeration value="Astronomy"/>
          <xs:enumeration value="Warfare"/>
          <xs:enumeration value="Rhetoric"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="anchor_text"/>
  </xs:attributeGroup>
  <xs:element name="language">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="position"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.language"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.language">
    <xs:attribute name="ident" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="position">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="marginalia_text"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="person"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="book"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="location"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="X-ref"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="emphasis"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="internal_ref"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.position"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.position">
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="book_orientation" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="0"/>
          <xs:enumeration value="90"/>
          <xs:enumeration value="180"/>
          <xs:enumeration value="270"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="marginalia_text" type="xs:string"/>
  <xs:element name="person">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.person"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.person">
    <xs:attribute name="name" use="required"/>
  </xs:attributeGroup>
  <xs:element name="book">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.book"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.book">
    <xs:attribute name="title" use="required"/>
  </xs:attributeGroup>
  <xs:element name="location">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.location"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.location">
    <xs:attribute name="name" use="required"/>
  </xs:attributeGroup>
  <xs:element name="X-ref">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.X-ref"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.X-ref">
    <xs:attribute name="person" use="required"/>
    <xs:attribute name="book_title" use="required"/>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="emphasis">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.emphasis"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.emphasis">
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="straight"/>
          <xs:enumeration value="curved"/>
          <xs:enumeration value="dotted"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="internal_ref">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="target"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.internal_ref"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.internal_ref">
    <xs:attribute name="text"/>
    <xs:attribute name="anchor_text"/>
  </xs:attributeGroup>
  <xs:element name="target">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.target"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.target">
    <xs:attribute name="filename" use="required"/>
    <xs:attribute name="book_id" use="required"/>
    <xs:attribute name="text" use="required"/>
  </xs:attributeGroup>
  <xs:element name="translation" type="xs:string"/>
  <xs:element name="underline">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.underline"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.underline">
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
          <xs:enumeration value="scoring"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="straight"/>
          <xs:enumeration value="curved"/>
          <xs:enumeration value="dotted"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  
  <xs:element name="substitution">    <!-- Added entire element for Reading Hamlet -->
    <xs:complexType>
      <xs:attributeGroup ref="attlist.substitution"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.substitution">
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="pen"/>
          <xs:enumeration value="pencil"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="replacement"/>
          <xs:enumeration value="insertion"/>
          <xs:enumeration value="deletion"/>
          <xs:enumeration value="errata"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="copyText" use="required"/>
    <xs:attribute name="amendedText" use="required"/>
  </xs:attributeGroup>
  
  <xs:element name="symbol">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.symbol"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.symbol">
    <xs:attribute name="name" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Asterisk"/>
          <xs:enumeration value="Bisected_circle"/>
          <xs:enumeration value="Crown"/>
          <xs:enumeration value="JC"/>
          <xs:enumeration value="Hatching"/>  <!-- Added for Reading Hamlet -->
          <xs:enumeration value="HT"/>
          <xs:enumeration value="LL"/>
          <xs:enumeration value="Mars"/>
          <xs:enumeration value="Mercury"/>
          <xs:enumeration value="Moon"/>
          <xs:enumeration value="Opposite_planets"/>
          <xs:enumeration value="Saturn"/>
          <xs:enumeration value="Square"/>
          <xs:enumeration value="SS"/>
          <xs:enumeration value="Sun"/>
          <xs:enumeration value="Venus"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="mark">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.mark"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.mark">
    <xs:attribute name="name" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="apostrophe"/>
          <xs:enumeration value="box"/>
          <xs:enumeration value="bracket"/>
          <xs:enumeration value="circumflex"/>
          <xs:enumeration value="colon"/>
          <xs:enumeration value="comma"/>
          <xs:enumeration value="dash"/>
          <xs:enumeration value="diacritic"/>
          <xs:enumeration value="dot"/>
          <xs:enumeration value="double_vertical_bar"/>
          <xs:enumeration value="equal_sign"/>
          <xs:enumeration value="est_mark"/>
          <xs:enumeration value="hash"/>
          <xs:enumeration value="horizontal_bar"/>
          <xs:enumeration value="page_break"/>
          <xs:enumeration value="pen_trial"/>
          <xs:enumeration value="plus_sign"/>
          <xs:enumeration value="quotation_mark"/>
          <xs:enumeration value="scribble"/>
          <xs:enumeration value="section_sign"/>
          <xs:enumeration value="semicolon"/>
          <xs:enumeration value="slash"/>
          <xs:enumeration value="straight_quotation_mark"/>
          <xs:enumeration value="tick"/>
          <xs:enumeration value="tilde"/>
          <xs:enumeration value="triple_dash"/>
          <xs:enumeration value="vertical_bar"/>
          <xs:enumeration value="X_sign"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="numeral">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.numeral"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.numeral">
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="errata">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.errata"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.errata">
    <xs:attribute name="language" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="copytext" use="required"/>
    <xs:attribute name="amendedtext" use="required"/>
  </xs:attributeGroup>
  <xs:element name="drawing">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.drawing"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.drawing">
    <xs:attribute name="name" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="face"/>
          <xs:enumeration value="manicule"/>
          <xs:enumeration value="florilegium"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
</xs:schema>

=== ChrisRG/ReadingHamlet/Hamlet.043v.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE transcription SYSTEM "http://www.livesandletters.ac.uk/schema/aor_20141023.dtd">

<transcription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/ChrisRG/ReadingHamlet/master/RHschema.xsd">
    
    <page filename="Hamlet.002r.tif" pagination="86" signature="V.2" reader="John Ward"/> <!-- Signature = act + scene -->
    <annotation>
        <!-- Marginalia --> 	<!-- Positions available: head, intext, tail, left_margin, right_margin -->
        <marginalia>
            <language ident="EN">
                <position place="left_margin" book_orientation="0">
                    <marginalia_text>
                        (8)
                        Ostrick Drum to beat a march
                    </marginalia_text>
                    <person name="Ostrick"/>
                </position>
            </language>
        </marginalia>
        
        <marginalia>
            <language ident="EN">
                <position place="left_margin" book_orientation="0">
                    <marginalia_text>
                       Ring 
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
        
        <marginalia>
            <language ident="EN">
                <position place="right_margin" book_orientation="0">
                    <marginalia_text>
                        Exit Ostrick
                </position>
            </language>
        </marginalia>
        
        <!-- Substitutions -->
        <substitution method="pen" type="insertion" copyText="The point envenom d too then venom to thy work." amendedText="The point envenom d too? then venom to thy work."/>
        
        <substitution method="pen" type="deletion" copyText="All, treafon, treafon" amendedText=""/>
        
        <substitution method="pen" type="deletion" copyText="Drink off this potion is the onyx have?" amendedText=""/>
        
        <substitution method="pen" type="deletion" copyText="He is jufily sery' d, it is a poison comper'd by himself." amendedText=""/>
        
        <substitution method="pen" type="insertion" copyText="Heaven make thee free of it I follow thee:" amendedText="Heaven make thee free of it! I follow thee:"/>		
        
        <substitution method="pen" type="replacement" copyText="I am dead Horatio, wretched Queen farewel." amendedText=",wretched Queen, farewel."/>
        
        <substitution method="pen" type="replacement" copyText="But let it be, Horatio I am dead," amendedText="But let it be Horatio,"/>
        
        <substitution method="pen" type="insertion" copyText="O Horatio what wounded name," amendedText="O good Horatio what wounded name,"/>
        
        <substitution method="pen" type="insertion" copyText="The embassadors of England give this warlike volley." amendedText="To the embassadors of England gives this warlike volley."/>
        <!-- Symbols and marks -->	<!-- Positions available: head, intext, tail, left_margin, right_margin -->
        <symbol name="Hatching" place="left_margin"/> 
        
        
    </annotation>
</transcription>

=== ChrisRG/ReadingHamlet/Hamlet.039v.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE transcription SYSTEM "http://www.livesandletters.ac.uk/schema/aor_20141023.dtd">

<transcription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/ChrisRG/ReadingHamlet/master/RHschema.xsd">
    
    <page filename="Hamlet.039v.tif" pagination="78" signature="V.1" reader="John Ward"/> <!-- Signature = act + scene -->
    <annotation>
         
        <!-- Substitutions -->
        <substitution method="pen" type="replacement" copyText="
            What is he whose grief | 
            Bears such an emphasis, whose phrase of sorrow" amendedText="
            What is he, whose griefs | 
            Bears such an emphasis? whose phrase of sorrow" />        
                
        <substitution method="pen" type="replacement" copyText="
            Ham. Thou pray'st not well: I prethee take thy fingers from my throat, |
            For though I am not spleenative and rash," amendedText="
            Ham. Thou pray'st not well: I prethee take thy fingers from my throat, -- |
            For though I am not spleenative and rash;" />        
        
        <substitution method="pen" type="deletion" copyText="
            Qu. Hamlet, Hamlet. | 
            All. Gentlemen. | 
            Hora. Good my Lord be quiet. " amendedText=""/> 
        
        <substitution method="pen" type="deletion" copyText="
            King. O he is mad Laertes. | 
            Qu. Forbear him." amendedText=""/>    
        
        <substitution method="pen" type="replacement" copyText="
            Ham. Shew me what thou't do, | 
            Wilt weep, wilt fight, wilt fast, wilt tear thy self, | 
            Wilt drink up Esil, eat a Crocodile? | 
            I'll do't; doest thou come here to whine? |
            To out-face me with leaping in her grave? |
            Be buried quick with her: and so will I; |
            And if thou prate of mountains, let them throw |
            Millions of acres on us, till our ground |
            Sindging his pate against the burning Zone, |
            Make Ossa like a wart; nay, and thou'lt mouth |
            I'll rant as well as thou." 
            amendedText="
            Ham. Shew me what thou'lt do, | 
            Wilt weep? wilt fight? wilt fast? wilt tear thy self? | 
            Wilt drink up Eisil, eat a Crocodile? | 
            I'll do't--doest thou come here to whine? |
            To out-face me with leaping in her grave? |
            Be buried quick with her, and so will I; |
            And if thou prate of mountains, let them throw |
            Millions of acres on us, till our ground, |
            Sindging his pate against the burning Zone, |
            Make Ossa like a wart! nay, and thou'lt mouth, |
            I'll rant as well as thou." />                
        
    </annotation>
</transcription>

=== ChrisRG/ReadingHamlet/Hamlet.010r.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE transcription SYSTEM "http://www.livesandletters.ac.uk/schema/aor_20141023.dtd">

<transcription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/ChrisRG/ReadingHamlet/master/RHschema.xsd">
    
    <page filename="Hamlet.010r.tif" pagination="19" signature="I.5" reader="John Ward"/> <!-- Signature = act + scene -->
    <annotation>
        <!-- Marginalia --> 	<!-- Positions available: head, intext, tail, left_margin, right_margin -->
        <marginalia>
            <language ident="EN">
                <position place="right_margin" book_orientation="0">
                    <marginalia_text>
                        (14)
                        Horatio
                        Marcellus
                    </marginalia_text>
                    <person name="Horatio"/>
                    <person name="Marcellus"/>
                </position>
            </language>
        </marginalia>
        
        <marginalia anchor_text="Farewel, rememeber."> 
            <language ident="EN">
                <position place="right_margin" book_orientation="0">
                    <marginalia_text>
                       Sinks
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
        
        <marginalia>
            <language ident="EN">
                <position place="right_margin" book_orientation="0">
                    <marginalia_text>
                        (15)
                       Ghost
                       under the
                       stage
                    </marginalia_text>
                    <person name="Ghost"/>
                </position>
            </language>
        </marginalia>
        
        <!-- Substitutions -->
        <substitution method="pen" type="deletion" copyText="
            &quot; Though lewdness court it in a shape of heaven, |
            &quot; So but though to a radiant angle linkâ€™t, |
            &quot; Will sort it self in a celestial bed, |
            &quot; And prey on garbage." amendedText=""/>
        
        <substitution method="pen" type="deletion" copyText="&quot; And curd, like eager droppings into milk," amendedText=""/>
        
        <substitution method="pen" type="deletion" copyText="
            And a most instant Tetter barkt about | 
            Most Lazar like, with vile and loathsome crust | 
            All my smooth body." amendedText=""/>
        
        <substitution method="pen" type="deletion" copyText="&quot; Unnuzled, disappointed, un aneald," amendedText=""/>
        
        <substitution method="pen" type="deletion" copyText="&quot; O horrible, O horrible, most horrible," amendedText=""/>
        
        <substitution method="pen" type="deletion" copyText="
            &quot; Ham. O all you host of heaven! O earth! what else? | 
            &quot; And shall I couple hell? O fie! &quot; hold my heart," amendedText="hold my heart,"/>
        
        <substitution method="pen" type="replacement" copyText="
            But bear me strongly up; remember thee! | 
            I thou poor Ghost, whiles memory holds a seat | 
            In this distracted Globe: remember thee!" 
            
            amendedText="But bear me strongly up; remember thee!-- 
            | I thou, poor Ghost, whilest memory holds a seat | 
            In this distracted Globe; remember thee!--"/>		
        
    </annotation>
</transcription>
