=== ChrisRG/ReadingHamlet/RHschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="transcription">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="page"/>
        <xs:element ref="annotation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="page">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.page"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.page">
    <xs:attribute name="filename" use="required"/>
    <xs:attribute name="pagination" use="required"/>  <!-- Made required for Reading Hamlet -->
    <xs:attribute name="signature"/>
    <xs:attribute name="reader" use="required"/>
  </xs:attributeGroup>
  <xs:element name="annotation">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="marginalia"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="substitution"/> <!-- Added for Reading Hamlet-->
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="underline"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="symbol"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="mark"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="numeral"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="errata"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="drawing"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="marginalia">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="language"/>
        <xs:element minOccurs="0" ref="translation"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.marginalia"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.marginalia">
    <xs:attribute name="hand"> <!-- Removed requirement for Reading Hamlet -->
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="English_secretary"/>
          <xs:enumeration value="Italian"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="marginalia_id"/>
    <xs:attribute name="marginalia_continues_to"/>
    <xs:attribute name="marginalia_continues_from"/>
    <xs:attribute name="marginalia_to_transcription"/>
    <xs:attribute name="marginalia_from_transcription"/>
    <xs:attribute name="book_id"/>
    <xs:attribute name="date"/>
    <xs:attribute name="other_reader"/>
    <xs:attribute name="topic">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Law"/>
          <xs:enumeration value="Astronomy"/>
          <xs:enumeration value="Warfare"/>
          <xs:enumeration value="Rhetoric"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="anchor_text"/>
  </xs:attributeGroup>
  <xs:element name="language">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="position"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.language"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.language">
    <xs:attribute name="ident" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="position">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="marginalia_text"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="person"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="book"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="location"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="X-ref"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="emphasis"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="internal_ref"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.position"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.position">
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="book_orientation" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="0"/>
          <xs:enumeration value="90"/>
          <xs:enumeration value="180"/>
          <xs:enumeration value="270"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="marginalia_text" type="xs:string"/>
  <xs:element name="person">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.person"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.person">
    <xs:attribute name="name" use="required"/>
  </xs:attributeGroup>
  <xs:element name="book">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.book"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.book">
    <xs:attribute name="title" use="required"/>
  </xs:attributeGroup>
  <xs:element name="location">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.location"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.location">
    <xs:attribute name="name" use="required"/>
  </xs:attributeGroup>
  <xs:element name="X-ref">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.X-ref"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.X-ref">
    <xs:attribute name="person" use="required"/>
    <xs:attribute name="book_title" use="required"/>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="emphasis">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.emphasis"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.emphasis">
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="straight"/>
          <xs:enumeration value="curved"/>
          <xs:enumeration value="dotted"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="internal_ref">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="target"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.internal_ref"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.internal_ref">
    <xs:attribute name="text"/>
    <xs:attribute name="anchor_text"/>
  </xs:attributeGroup>
  <xs:element name="target">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.target"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.target">
    <xs:attribute name="filename" use="required"/>
    <xs:attribute name="book_id" use="required"/>
    <xs:attribute name="text" use="required"/>
  </xs:attributeGroup>
  <xs:element name="translation" type="xs:string"/>
  <xs:element name="underline">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.underline"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.underline">
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
          <xs:enumeration value="scoring"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="straight"/>
          <xs:enumeration value="curved"/>
          <xs:enumeration value="dotted"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  
  <xs:element name="substitution">    <!-- Added entire element for Reading Hamlet -->
    <xs:complexType>
      <xs:attributeGroup ref="attlist.substitution"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.substitution">
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="pen"/>
          <xs:enumeration value="pencil"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="replacement"/>
          <xs:enumeration value="insertion"/>
          <xs:enumeration value="deletion"/>
          <xs:enumeration value="errata"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="copyText" use="required"/>
    <xs:attribute name="amendedText" use="required"/>
  </xs:attributeGroup>
  
  <xs:element name="symbol">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.symbol"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.symbol">
    <xs:attribute name="name" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Asterisk"/>
          <xs:enumeration value="Bisected_circle"/>
          <xs:enumeration value="Crown"/>
          <xs:enumeration value="JC"/>
          <xs:enumeration value="Hatching"/>  <!-- Added for Reading Hamlet -->
          <xs:enumeration value="HT"/>
          <xs:enumeration value="LL"/>
          <xs:enumeration value="Mars"/>
          <xs:enumeration value="Mercury"/>
          <xs:enumeration value="Moon"/>
          <xs:enumeration value="Opposite_planets"/>
          <xs:enumeration value="Saturn"/>
          <xs:enumeration value="Square"/>
          <xs:enumeration value="SS"/>
          <xs:enumeration value="Sun"/>
          <xs:enumeration value="Venus"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="mark">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.mark"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.mark">
    <xs:attribute name="name" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="apostrophe"/>
          <xs:enumeration value="box"/>
          <xs:enumeration value="bracket"/>
          <xs:enumeration value="circumflex"/>
          <xs:enumeration value="colon"/>
          <xs:enumeration value="comma"/>
          <xs:enumeration value="dash"/>
          <xs:enumeration value="diacritic"/>
          <xs:enumeration value="dot"/>
          <xs:enumeration value="double_vertical_bar"/>
          <xs:enumeration value="equal_sign"/>
          <xs:enumeration value="est_mark"/>
          <xs:enumeration value="hash"/>
          <xs:enumeration value="horizontal_bar"/>
          <xs:enumeration value="page_break"/>
          <xs:enumeration value="pen_trial"/>
          <xs:enumeration value="plus_sign"/>
          <xs:enumeration value="quotation_mark"/>
          <xs:enumeration value="scribble"/>
          <xs:enumeration value="section_sign"/>
          <xs:enumeration value="semicolon"/>
          <xs:enumeration value="slash"/>
          <xs:enumeration value="straight_quotation_mark"/>
          <xs:enumeration value="tick"/>
          <xs:enumeration value="tilde"/>
          <xs:enumeration value="triple_dash"/>
          <xs:enumeration value="vertical_bar"/>
          <xs:enumeration value="X_sign"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="numeral">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.numeral"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.numeral">
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="errata">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.errata"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.errata">
    <xs:attribute name="language" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="copytext" use="required"/>
    <xs:attribute name="amendedtext" use="required"/>
  </xs:attributeGroup>
  <xs:element name="drawing">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.drawing"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.drawing">
    <xs:attribute name="name" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="face"/>
          <xs:enumeration value="manicule"/>
          <xs:enumeration value="florilegium"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
</xs:schema>

=== ChrisRG/ReadingHamlet/Hamlet.039r.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE transcription SYSTEM "http://www.livesandletters.ac.uk/schema/aor_20141023.dtd">

<transcription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/ChrisRG/ReadingHamlet/master/RHschema.xsd">
    
    <page filename="Hamlet.039r.tif" pagination="77" signature="V.1" reader="John Ward"/> <!-- Signature = act + scene -->
    <annotation>
         
        
        <!-- Substitutions -->
        
        <substitution method="pen" type="replacement" copyText="
            Ham. No faith not a jot but to follow him thither with 
            modestly enough, and likelihood to lead it: Alexander died, Alexander was 
            buried, Alexander returneth to dust, the dust is earth, of earth we 
            make lome, and why of that lome whereto he was converted might 
            they not stop a Beer-barrel? |
            Imperious Caesar dead and turned to clay | 
            Might stop a hole to keep the wind away, | 
            O that that earth which kept the world in awe, |
            Should patch a wall t'expel the waters flaw! | 
            But soft, but soft a while, here comes the King, | 
            The Queen, the Courters: who is this they follow, |
            And with such maimed rites? this doth betoken, |
            The coarse they follow did with desperate hand |
            Fordo its own life, 'twas of some estate: |
            Stand by a while and mark.
            " amendedText="
            Ham. No faith, not a jot: but to follow him thither with 
            modestly enough, as thus Alexander died, Alexander was 
            buried, Alexander returneth to dust; the dust is earth: of earth we 
            make lome; and why of that lome, whereto he was converted, might 
            they not stop a Beer-barrel? |
            Imperiall Caesar dead and turned to clay, | 
            Might stop a hole to keep the wind away; | 
            O, that that earth, which kept the world in awe, |
            Should patch a wall, t'expel the waters flaw! | 
            But soft, a while-here comes the King, | 
            The Queen, the Courters: who is this they follow, |
            And with such maimed rites? this doth betoken, |
            The coarse, they follow did with desperate hand |
            Fordo its own life, |
            Stand by a while, and mark."/>
                
        <substitution method="pen" type="insertion" copyText="
            Ham. This is Laertes a very noble youth." amendedText="
            Ham. This is Laertes a very noble youth.--"/>        
        
        <substitution method="pen" type="deletion" copyText= "
            Doct. Her obsequies have been as far inlarg'd |
            As we have warranty; her death was doubtful, | 
            And but that great command o're-sways the order, | 
            She should in ground unstanctified been lodg'd: | 
            For charitable prayers, | 
            Flints and pebbles should be thrown on her, | 
            Yet here she is allow'd her virgin rites, | 
            Her maiden strewments, and the bringing home | 
            Of bell and burial." amendedText="
            Doct. Her obsequies have been as far inlarg'd |
            As we have warranty;"/>
        
        <substitution method="pen" type="deletion" copyText= "
            Doct. No more: |
            We should profane the service of the dead | 
            To sing a Requiem and such reft to her | 
            As to peace-parted souls." amendedText="
            Doct. No more:"/>
        
        <substitution method="pen" type="replacement" copyText= "
            Ham. What? the fair Ophelia?" amendedText="Ham. What, the fair Ophelia?"/>
        
        <!-- Symbols and marks -->    <!-- Positions available: head, intext, tail, left_margin, right_margin -->
        
        <symbol name="Hatching" place="right_margin"/>
        
                
    </annotation>
</transcription>

=== ChrisRG/ReadingHamlet/Hamlet.026r.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE transcription SYSTEM "http://www.livesandletters.ac.uk/schema/aor_20141023.dtd">

<transcription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/ChrisRG/ReadingHamlet/master/RHschema.xsd">
    
    <page filename="Hamlet.026r.tif" pagination="51" signature="III.3" reader="John Ward"/> <!-- Signature = act + scene -->
    <annotation>
        <!-- Marginalia --> 	<!-- Positions available: head, intext, tail, left_margin, right_margin -->
        <marginalia>
            <language ident="EN">
                <position place="right_margin" book_orientation="0">
                    <marginalia_text>
                        (17)
                        Queen 
                        Polonius
                        2 Chairs on
                    </marginalia_text>
                    <person name="Queen"/>
                    <person name="Polonius"/>
                </position>
            </language>
        </marginalia>
        
        <substitution method="pen" type="insertion" copyText="&quot; Offences guided hand may shew by justice," amendedText="&quot; Offences guilded hand may shew by justice,"/>
        
        <substitution method="pen" type="insertion" copyText="
            Ham. Where is this murderer, he kneels and prays, | 
            And now I'll do't, and so he goes to heaven, |
            And so am I reveng'd? that would be scann'd; |
            He kill'd my father; and for that |
            I his sole son send him |
            To heaven: |
            Why this is a reward, -- not revenge:"
            amendedText="
            Ham. Where is this murderer? he kneels and prays, | 
            And now I'll do't - and so he goes to heaven,-- |
            And so am I reveng'd? that would be scann'd;-- |
            He kill'd my father;-and for that, |
            I, his sole son, send him |
            To heaven-- |
            Why this is reward, &amp; not revenge:"/>
            
        
        <!-- Symbols and marks -->	<!-- Positions available: head, intext, tail, left_margin, right_margin -->
        <symbol name="Hatching" place="right_margin" text="[Enter Hamlet."/> 
        
        
    </annotation>
</transcription>
