=== ChrisRG/ReadingHamlet/RHschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="transcription">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="page"/>
        <xs:element ref="annotation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="page">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.page"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.page">
    <xs:attribute name="filename" use="required"/>
    <xs:attribute name="pagination" use="required"/>  <!-- Made required for Reading Hamlet -->
    <xs:attribute name="signature"/>
    <xs:attribute name="reader" use="required"/>
  </xs:attributeGroup>
  <xs:element name="annotation">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="marginalia"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="substitution"/> <!-- Added for Reading Hamlet-->
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="underline"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="symbol"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="mark"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="numeral"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="errata"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="drawing"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="marginalia">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="language"/>
        <xs:element minOccurs="0" ref="translation"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.marginalia"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.marginalia">
    <xs:attribute name="hand"> <!-- Removed requirement for Reading Hamlet -->
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="English_secretary"/>
          <xs:enumeration value="Italian"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="marginalia_id"/>
    <xs:attribute name="marginalia_continues_to"/>
    <xs:attribute name="marginalia_continues_from"/>
    <xs:attribute name="marginalia_to_transcription"/>
    <xs:attribute name="marginalia_from_transcription"/>
    <xs:attribute name="book_id"/>
    <xs:attribute name="date"/>
    <xs:attribute name="other_reader"/>
    <xs:attribute name="topic">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Law"/>
          <xs:enumeration value="Astronomy"/>
          <xs:enumeration value="Warfare"/>
          <xs:enumeration value="Rhetoric"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="anchor_text"/>
  </xs:attributeGroup>
  <xs:element name="language">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="position"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.language"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.language">
    <xs:attribute name="ident" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="position">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="marginalia_text"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="person"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="book"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="location"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="X-ref"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="emphasis"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="internal_ref"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.position"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.position">
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="book_orientation" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="0"/>
          <xs:enumeration value="90"/>
          <xs:enumeration value="180"/>
          <xs:enumeration value="270"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="marginalia_text" type="xs:string"/>
  <xs:element name="person">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.person"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.person">
    <xs:attribute name="name" use="required"/>
  </xs:attributeGroup>
  <xs:element name="book">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.book"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.book">
    <xs:attribute name="title" use="required"/>
  </xs:attributeGroup>
  <xs:element name="location">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.location"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.location">
    <xs:attribute name="name" use="required"/>
  </xs:attributeGroup>
  <xs:element name="X-ref">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.X-ref"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.X-ref">
    <xs:attribute name="person" use="required"/>
    <xs:attribute name="book_title" use="required"/>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="emphasis">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.emphasis"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.emphasis">
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="straight"/>
          <xs:enumeration value="curved"/>
          <xs:enumeration value="dotted"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="internal_ref">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="target"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.internal_ref"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.internal_ref">
    <xs:attribute name="text"/>
    <xs:attribute name="anchor_text"/>
  </xs:attributeGroup>
  <xs:element name="target">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.target"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.target">
    <xs:attribute name="filename" use="required"/>
    <xs:attribute name="book_id" use="required"/>
    <xs:attribute name="text" use="required"/>
  </xs:attributeGroup>
  <xs:element name="translation" type="xs:string"/>
  <xs:element name="underline">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.underline"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.underline">
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
          <xs:enumeration value="scoring"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="straight"/>
          <xs:enumeration value="curved"/>
          <xs:enumeration value="dotted"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  
  <xs:element name="substitution">    <!-- Added entire element for Reading Hamlet -->
    <xs:complexType>
      <xs:attributeGroup ref="attlist.substitution"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.substitution">
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="pen"/>
          <xs:enumeration value="pencil"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="replacement"/>
          <xs:enumeration value="insertion"/>
          <xs:enumeration value="deletion"/>
          <xs:enumeration value="errata"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="copyText" use="required"/>
    <xs:attribute name="amendedText" use="required"/>
  </xs:attributeGroup>
  
  <xs:element name="symbol">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.symbol"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.symbol">
    <xs:attribute name="name" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Asterisk"/>
          <xs:enumeration value="Bisected_circle"/>
          <xs:enumeration value="Crown"/>
          <xs:enumeration value="JC"/>
          <xs:enumeration value="Hatching"/>  <!-- Added for Reading Hamlet -->
          <xs:enumeration value="HT"/>
          <xs:enumeration value="LL"/>
          <xs:enumeration value="Mars"/>
          <xs:enumeration value="Mercury"/>
          <xs:enumeration value="Moon"/>
          <xs:enumeration value="Opposite_planets"/>
          <xs:enumeration value="Saturn"/>
          <xs:enumeration value="Square"/>
          <xs:enumeration value="SS"/>
          <xs:enumeration value="Sun"/>
          <xs:enumeration value="Venus"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="mark">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.mark"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.mark">
    <xs:attribute name="name" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="apostrophe"/>
          <xs:enumeration value="box"/>
          <xs:enumeration value="bracket"/>
          <xs:enumeration value="circumflex"/>
          <xs:enumeration value="colon"/>
          <xs:enumeration value="comma"/>
          <xs:enumeration value="dash"/>
          <xs:enumeration value="diacritic"/>
          <xs:enumeration value="dot"/>
          <xs:enumeration value="double_vertical_bar"/>
          <xs:enumeration value="equal_sign"/>
          <xs:enumeration value="est_mark"/>
          <xs:enumeration value="hash"/>
          <xs:enumeration value="horizontal_bar"/>
          <xs:enumeration value="page_break"/>
          <xs:enumeration value="pen_trial"/>
          <xs:enumeration value="plus_sign"/>
          <xs:enumeration value="quotation_mark"/>
          <xs:enumeration value="scribble"/>
          <xs:enumeration value="section_sign"/>
          <xs:enumeration value="semicolon"/>
          <xs:enumeration value="slash"/>
          <xs:enumeration value="straight_quotation_mark"/>
          <xs:enumeration value="tick"/>
          <xs:enumeration value="tilde"/>
          <xs:enumeration value="triple_dash"/>
          <xs:enumeration value="vertical_bar"/>
          <xs:enumeration value="X_sign"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="numeral">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.numeral"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.numeral">
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="errata">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.errata"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.errata">
    <xs:attribute name="language" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="copytext" use="required"/>
    <xs:attribute name="amendedtext" use="required"/>
  </xs:attributeGroup>
  <xs:element name="drawing">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.drawing"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.drawing">
    <xs:attribute name="name" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="face"/>
          <xs:enumeration value="manicule"/>
          <xs:enumeration value="florilegium"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
</xs:schema>

=== ChrisRG/ReadingHamlet/Hamlet.038v.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE transcription SYSTEM "http://www.livesandletters.ac.uk/schema/aor_20141023.dtd">

<transcription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/ChrisRG/ReadingHamlet/master/RHschema.xsd">
    
    <page filename="Hamlet.038v.tif" pagination="76" signature="V.1" reader="John Ward"/> <!-- Signature = act + scene -->
    <annotation>
        <!-- Marginalia -->     <!-- Positions available: head, intext, tail, left_margin, right_margin -->
        <marginalia>
            <language ident="EN">
                <position place="left_margin" book_orientation="0">
                    <marginalia_text>
                        (3)
                        King
                        Queen
                        Laertes
                        Priest
                        Attendants
                        Corpse Supported
                    </marginalia_text>
                    <person name="King"/>
                    <person name="Queen"/>
                    <person name="Laertes"/>
                    <person name="Priest"/>
                    <person name="Attendants"/>
                </position>
            </language>
        </marginalia>
        <marginalia >
            <language ident="EN">
                <position place="left_margin" book_orientation="90">
                    <marginalia_text>
                        Hamlet Prince of Denmark    <!-- Probably a different hand -->
                    </marginalia_text>
                    <person name="Hamlet"/>
                </position>
            </language>
        </marginalia>
        
        <marginalia anchor_text= "And smelt so? Pah." >
            <language ident="EN">
                <position place="intext" book_orientation="0">
                    <marginalia_text>
                        Smelling to the scull
                    </marginalia_text>
                </position>
            </language>
        </marginalia>
       
        
        <!-- Substitutions -->
        <substitution method="pen" type="replacement" copyText="
            Ha. Alas poor Yorick. I knew him Horatio, a fellow of infinite
            jest, of most excellent fancy, he hath bore me on his back a thousand 
            times, and now how abhorred in my imagination it is? my gorge 
            rises at it. Here hung those lips that I have kist I know not how 
            oft: where be your jibes now, your jests, your songs, your flashes of
            merriment, that were wont to set the table on a roar? not one now 
            to mock your own grinning? quite chopfaln? Now get you to
            my Ladies table, and tell her, let her paint an inch thick, to this 
            favour she must come; Make her laugh at that,
            Prethee Horatio, tell me one thing." amendedText="
            
            Ha. Alas poor Yorick! I knew him, Horatio, a fellow of infinite
            jest; of most excellent fancy: he hath bore me in his arms a thousand 
            times: Here hung those lips, that I have kist I know not how 
            oft: where be your jibes now? your jests? your songs? your flashes of 
            merriment, that were wont to set the table in a roar? not one now, 
            to mock your own grinning? quite chopfaln? Now get you to
            my Ladies table, and tell her, let her paint an inch thick, to this 
            favour she must come; 
            Prethee, Horatio, tell me one thing."/>
        
        <substitution method="pen" type="insertion" copyText="
            Ham. Dost thou think Alexander lookt on this fashion i'th' earth?" 
            
            amendedText="
            Ham. Dost thou think, Alexander lookt o' this fashion i'th' earth?" />
        
        <substitution method="pen" type="insertion" copyText="
            Ham. To what base uses we may return Horatio! why may not 
            imagination trace the noble dust of Alexander till he find it 
            stopping a bung hole." amendedText="
                
            Ham. To what base uses we may return, Horatio! why may not 
            imagination trace the noble dust of Alexander, till he find it 
            stopping a bung hole."/>             
    </annotation>
</transcription>

=== ChrisRG/ReadingHamlet/Hamlet.041r.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE transcription SYSTEM "http://www.livesandletters.ac.uk/schema/aor_20141023.dtd">

<transcription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/ChrisRG/ReadingHamlet/master/RHschema.xsd">
    
    <page filename="Hamlet.041r.tif" pagination="81" signature="V.2" reader="John Ward"/> <!-- Signature = act + scene -->
    <annotation>
        
        <substitution method="pen" type="replacement" copyText="
            methinks it is very soultry and hot, or my 
            complexion." amendedText="
            methinks it is very soultry and hot, for my
            complexion.--"/>
        
        <substitution method="pen" type="replacement" copyText="
            Court. Exceedingly my Lord, it is very soultry, as 'twere I cannot
            tell how. My Lord, his Majesty had me signifie unto you that
            he has laid a great wager on your head, Sir this is the matter." amendedText="
            Ost. Exceedingly my Lord, it is very soultry, as 'twere I cannot
            tell how. My Lord, his Majesty had me signifie unto you that
            he has laid a great wager on your head. Sir this is the matter.--"/>
        
        <substitution method="pen" type="replacement" copyText="Court." amendedText="Ost."/>
        
        <substitution method="pen" type="replacement" copyText="
            Ham. Sir, his definement suffers no loss in you, though I know
            to divide him inventorially, would dizzy th' arithmetick of memory, 
            and yet but raw neither in respect of his quick sail; but in the
            verity of extolment I take him to be a soul of great article, and his 
            infusion of such dearth and rareness, as to make true diction of 
            him, his semblable is his mirrour, and who else would trace him, 
            his umbrage, nothing more. |
            Court. Your Lordship speaks most infallibly of him. |
            Ham. The concernancy Sir, why do we wrap the Gentleman in
            our rawer breath? |
            Court. Sir. |
            Hora. Is't not possible to understand in another tongue, you will
            do't Sir really. |
            Ham. What imports the nomination of this Gentleman?" 
            
            amendedText="
            Ham. Sir, his definement suffers no loss in you, though I know
            to divide him inventorially, would dizzy th' arithmetick of memory, 
            but in the
            verity of extolment, I take him to be a soul of great article.
            Ost. Your Lordship speaks most infallibly of him. |
            Ham. The concernancy, Sir? why do we wrap the Gentleman in
            our rawer breath? |
            Ost. Sir.-- |
            Ham. What imports the nomination of this Gentleman?"/>
        
        <substitution method="pen" type="deletion" copyText="
            Ham. Sir, his definement suffers no loss in you, though I know
            to divide him inventorially, would dizzy th' arithmetick of memory, 
            but in the
            verity of extolment, I take him to be a soul of great article.
            Ost. Your Lordship speaks most infallibly of him. |
            Ham. The concernancy, Sir? why do we wrap the Gentleman in
            our rawer breath? |
            Ost. Sir.-- |
            Ham. What imports the nomination of this Gentleman?" 
            
            amendedText="Ham. What imports the nomination of this Gentleman?"/>
            
        <substitution method="pen" type="replacement" copyText="
            Court. Of Laertes?" amendedText="
            Ost. Of Laertes?"/>
        
        <substitution method="pen" type="deletion" copyText="
            Ham. His purse is empty already, all's golden words are spent." amendedText=""/>
        
        <substitution method="pen" type="deletion" copyText="
            Court. I know you are not ignorant. |
            Ham. I would you did Sir, yet if you did it would not much
            approve me: well Sir." amendedText=""/>
        
    </annotation>
</transcription>
